"""Public API for the arXiv literature reviewer."""

from .analysis import (
    RELEVANCE_TEXT_CHARS,
    advance_paper_node,
    extract_core_node,
    relevance_eval_node,
    route_after_advance_paper,
    route_after_extract_core,
    route_after_relevance_eval,
)
from .gemini_client import (
    GEMINI_MODEL,
    generate_structured,
    generate_text,
    gemini_llm,
)
from .rag import (
    CHUNK_OVERLAP,
    CHUNK_SIZE,
    DEFAULT_DATA_DIR,
    DEFAULT_TOP_K,
    EMBEDDING_MODEL,
    RETRIEVER_KINDS,
    build_chunk_id,
    chunk_pages,
    dense_retriever,
    get_embeddings,
    get_retriever,
    index_paper,
    ingest_node,
    open_store,
)
from .reporting import render_markdown_fallback, write_atomically, write_markdown_node
from .retrieval import (
    download_parse_node,
    make_search_plan,
    route_after_search,
    search_arxiv,
    search_node,
)
from .review_types import (
    LiteratureReview,
    PaperAnalysis,
    PaperMetadata,
    ParsedPage,
    ParsedPaper,
    RelevanceDecision,
    ReviewerState,
    SearchPlan,
)
from .workflow import (
    build_graph,
    checkpoint_db_path,
    open_checkpointer,
    persistent_graph,
    read_status,
    resume_reviewer,
    run_reviewer,
    thread_config,
    thread_exists,
)

__all__ = [
    "CHUNK_OVERLAP",
    "CHUNK_SIZE",
    "DEFAULT_DATA_DIR",
    "DEFAULT_TOP_K",
    "EMBEDDING_MODEL",
    "GEMINI_MODEL",
    "RELEVANCE_TEXT_CHARS",
    "RETRIEVER_KINDS",
    "LiteratureReview",
    "PaperAnalysis",
    "PaperMetadata",
    "ParsedPage",
    "ParsedPaper",
    "RelevanceDecision",
    "ReviewerState",
    "SearchPlan",
    "advance_paper_node",
    "build_chunk_id",
    "build_graph",
    "checkpoint_db_path",
    "chunk_pages",
    "dense_retriever",
    "download_parse_node",
    "extract_core_node",
    "gemini_llm",
    "generate_structured",
    "generate_text",
    "get_embeddings",
    "get_retriever",
    "index_paper",
    "ingest_node",
    "make_search_plan",
    "open_checkpointer",
    "open_store",
    "persistent_graph",
    "read_status",
    "relevance_eval_node",
    "render_markdown_fallback",
    "resume_reviewer",
    "route_after_advance_paper",
    "route_after_extract_core",
    "route_after_relevance_eval",
    "route_after_search",
    "run_reviewer",
    "search_arxiv",
    "search_node",
    "thread_config",
    "thread_exists",
    "write_atomically",
    "write_markdown_node",
]
